version: "3"

services:
  flight-api:
    build: .
    container_name: flight_aggregator
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: flight_redis
    ports:
      - "6379:6379"